#!/bin/bash

rmmod intercept 2> killedG.out >> killedG.out

gcc killerG.c -o killerG.out
gcc killedG.c -o killed1G.out
gcc killedG.c -o killed2G.out



#test #1 - always success
res=`./killerG.out`
echo -n "TEST#1:"
if [[ $res == "99" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi

#test #2 - always success
res=`./killerG.out 1 1`
echo -n "TEST#2:"
if [[ $res == "1515" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi

#test #3 - always success
res=`./killerG.out 0 1`
echo -n "TEST#3:"
if [[ $res == "915" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi

#test #4
insmod intercept.o
res=`./killerG.out`
echo -n "TEST#4:"
if [[ $res == "99" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #5
insmod intercept.o
res=`./killerG.out 0 1`
echo -n "TEST#5:"
if [[ $res == "915" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #6 + #7
insmod intercept.o program_name="killed1G.out"
res=`./killerG.out`
echo $res
echo -n "TEST#6:"
if [[ $res == "09" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
res=`./killerG.out`
echo -n "TEST#7:"
if [[ $res == "09" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #8
insmod intercept.o program_name="killed1G.out"
res=`./killerG.out 1 0`
echo -n "TEST#8:"
if [[ $res == "159" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #9
insmod intercept.o program_name="killed1G.out"
res=`./killerG.out 0 1`
echo -n "TEST#9:"
if [[ $res == "015" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #10
insmod intercept.o program_name="killed1G.out"
res=`./killerG.out 1 1`
echo -n "TEST#10:"
if [[ $res == "1515" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #11
insmod intercept.o program_name="killed2G.out"
res=`./killerG.out 1 0`
echo -n "TEST#11:"
if [[ $res == "150" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #12
insmod intercept.o program_name="killed2G.out"
res=`./killerG.out 0 1`
echo -n "TEST#12:"
if [[ $res == "915" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #13
insmod intercept.o program_name="killed2G.out"
res=`./killerG.out 1 1`
echo -n "TEST#13:"
if [[ $res == "1515" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #14
insmod intercept.o program_name="killegG.out"
res=`./killerG.out`
echo -n "TEST#14:"
if [[ $res == "99" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #15
insmod intercept.o program_name="killegG.out"
res=`./killerG.out 1 0`
echo -n "TEST#15:"
if [[ $res == "159" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi
rmmod intercept

#test #16 - always success
res=`./killerG.out`
echo -n "TEST#16:"
if [[ $res == "99" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi

#test #17 - always success
res=`./killerG.out 1 1`
echo -n "TEST#17:"
if [[ $res == "1515" ]]; then
	echo SUCCESS!
else
	echo FAILED!
fi